# Generated by Django 6.0.5 on 2026-06-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0002_alter_detectionlog_id_alter_uploadedvideo_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectionlog',
            options={'ordering': ['-detected_at']},
        ),
        migrations.AddField(
            model_name='detectionlog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='detection_logs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='detectionlog',
            name='activity_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('suspicious', 'Suspicious'), ('weapon_detected', 'Weapon Detected'), ('fight_detected', 'Fight Detected'), ('id_detected', 'ID Detected'), ('spoof_detected', 'Spoof Detected')], max_length=50),
        ),
    ]
