# Generated by Django 6.0.5 on 2026-06-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0003_alter_detectionlog_options_detectionlog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedvideo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded_images/'),
        ),
        migrations.AlterField(
            model_name='uploadedvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_videos/'),
        ),
    ]
